package com.cc.repo.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cc.repo.dao.GitHub;

import com.cc.repo.dao.GitHubDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gitHubDaoConfig;

    private final GitHubDao gitHubDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gitHubDaoConfig = daoConfigMap.get(GitHubDao.class).clone();
        gitHubDaoConfig.initIdentityScope(type);

        gitHubDao = new GitHubDao(gitHubDaoConfig, this);

        registerDao(GitHub.class, gitHubDao);
    }
    
    public void clear() {
        gitHubDaoConfig.getIdentityScope().clear();
    }

    public GitHubDao getGitHubDao() {
        return gitHubDao;
    }

}
